### PR TITLE
Major Markdown to Confluence Update

### PR DESCRIPTION
**Pull request by mineshpatel1**
Features new python script addressing the following issues:

* Special character escaping
* Parent page movement
* Page updates as well as creation
* Delete option
* Syntax highlighting on Code Blocks
* Custom markdown syntax for Confluence Info, Note and Warning macros
* Switched to REST API instead of deprecated XML RPC

### CODE REVIEW

**Comment by rmoff** [comment]
I'd like it if it defaulted to personal space again if not specified. Makes it easier to chuck docs up to Atlas quickly and sort out which space etc at a later date.

Also can you pull to develop instead? ta

**Comment by rmoff** [comment]
Nicely done though, BTW, big improvement on my hack job :+1:

**Comment by rmoff** [comment]
Where's it pulling the default page title from? Filename would be better (or is in my case - doc titles are the file names for me).

**Comment by rmoff** [comment]
Handled this very nicely, good work

https://rittmanmead.atlassian.net/wiki/display/TEC/Using+OBIEE+custom+skin+to+identify+separate+nodes?moved=true

**Comment by mineshpatel1** [comment]
Page title is the first line of the markdown file, which is usually the title in a markdown file. I changed this from file name because half of the docs are README.md's in git repositories. I'll had an -f option for file name titles if you want though.

I can add the personal space - is that like a user space? Do I just use a special space code?

I've also written GE a wrapper for pandoc so they can generate an effective website from markdown documents on their crappy file share space with their CSS. It's probably something handy for us for creating nice offline exports.

**Comment by rmoff** [comment]
Ok my bad, I should rtfm ;-)Personal space / user space yep same thing. Can't remember how to reference it but it's what my original code does by default if no space specified. 

My use case for the tool is publishing my own local notes that I do in nvalt to atlas, hence low friction requirement 

Pandoc sounds very interesting, I have a tex file and text expander snippet to auto build PDF with it but it's a hack so I suspect your polish would be good on it :) 


--

Robin Moffatt

Principal Consultant

M: +44 7841 207 265 • E: robin.moffatt@rittmanmead.com

S: robinmoffatt • T: @rmoff

www.rittmanmead.com




Registered Office : Suite B, First Floor, Moore House, 11 - 13 Black Lion Street, Brighton, BN1 1ND, United Kingdom




Company No. : 6032852

VAT No. : 900 3839 48




Please note that this email communication is intended only for the addressee and may contain confidential or privileged information. The contents of this email may be circulated internally within your organisation only and may not be communicated to third parties without the prior written permission of Rittman Mead Consulting.  This email is not intended nor should it be taken to create any legal relations, contractual or otherwise.

**Pull request closed without merging**
